
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'

export const UPDATE_CONVERSARTIONS = 'UPDATE_CONVERSARTIONS'
export const CLEAR_CONVERSARTIONS = 'CLEAR_CONVERSARTIONS'
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE'
export const LOAD_MORE_CONVERSATIONS = 'LOAD_MORE_CONVERSATIONS'

export const UPDATE_FCM_TOKEN = 'UPDATE_FCM_TOKEN'