
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'

export const UPDATE_CONVERSARTIONS = 'UPDATE_CONVERSARTIONS'
export const LOAD_MORE_CONVERSATIONS = 'LOAD_MORE_CONVERSATIONS'